// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAToiLCBYLu5R1L-EqjCpGCvk2-4wGGVYc',
    appId: '1:298417514202:web:45d2559cae7984cf76e7e3',
    messagingSenderId: '298417514202',
    projectId: 'tracer-f1497',
    authDomain: 'tracer-f1497.firebaseapp.com',
    storageBucket: 'tracer-f1497.firebasestorage.app',
    measurementId: 'G-NBFELHX7RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxKYdmARzJlBSu3ay7JulnvlK81oQBQbo',
    appId: '1:298417514202:android:97be2f3197f6295076e7e3',
    messagingSenderId: '298417514202',
    projectId: 'tracer-f1497',
    storageBucket: 'tracer-f1497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNSaZfq30W3vBIJ5paC3Rld1a4rN11IL8',
    appId: '1:298417514202:ios:4852476c4dbcdb6476e7e3',
    messagingSenderId: '298417514202',
    projectId: 'tracer-f1497',
    storageBucket: 'tracer-f1497.firebasestorage.app',
    iosBundleId: 'com.example.tracer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNSaZfq30W3vBIJ5paC3Rld1a4rN11IL8',
    appId: '1:298417514202:ios:4852476c4dbcdb6476e7e3',
    messagingSenderId: '298417514202',
    projectId: 'tracer-f1497',
    storageBucket: 'tracer-f1497.firebasestorage.app',
    iosBundleId: 'com.example.tracer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAToiLCBYLu5R1L-EqjCpGCvk2-4wGGVYc',
    appId: '1:298417514202:web:78892c558f4b679e76e7e3',
    messagingSenderId: '298417514202',
    projectId: 'tracer-f1497',
    authDomain: 'tracer-f1497.firebaseapp.com',
    storageBucket: 'tracer-f1497.firebasestorage.app',
    measurementId: 'G-KLH9635CH2',
  );
}
